// Marketing-site content (vaulmo.com), editable from the admin console CMS.
// Each page is stored by slug with a structured `content` object. These defaults seed
// the store and also act as the landing site's built-in fallback copy, so the site
// renders even before anything is edited (or if the API is briefly unreachable).

export interface SitePageSeed { slug: string; title: string; content: any }

export const SITE_PAGE_SLUGS = ['global', 'home', 'features', 'security', 'privacy', 'support', 'about', 'contact', 'faq', 'terms'] as const;

export const DEFAULT_SITE_PAGES: SitePageSeed[] = [
  {
    slug: 'global',
    title: 'Global',
    content: {
      brand: 'Vaulmo',
      tagline: 'Your family’s document vault, locked down',
      appUrl: 'https://app.vaulmo.com',
      appStoreUrl: '#',
      googlePlayUrl: '#',
      nav: [
        { label: 'Features', href: '#/features' },
        { label: 'Security', href: '#/security' },
        { label: 'Privacy', href: '#/privacy' },
        { label: 'Support', href: '#/support' },
        { label: 'About', href: '#/about' },
        { label: 'FAQs', href: '#/faq' },
        { label: 'Contact', href: '#/contact' },
      ],
      footerNote: '© 2026 Vaulmo. All rights reserved.',
      footerLinks: [
        { label: 'Features', href: '#/features' },
        { label: 'Security', href: '#/security' },
        { label: 'Support', href: '#/support' },
        { label: 'About', href: '#/about' },
        { label: 'Contact', href: '#/contact' },
        { label: 'Privacy Policy', href: '#/privacy' },
        { label: 'Terms & Conditions', href: '#/terms' },
      ],
      // Social links — paste full URLs; each icon only shows when its link is set.
      socials: { instagram: '', twitter: '', facebook: '' },
      // Waitlist sign-up form (shown top & bottom, and inside the launch popup).
      subscribe: {
        title: 'Be first to know',
        subtitle: 'Join the waitlist and we’ll tell you the moment Vaulmo launches.',
        namePlaceholder: 'Your name',
        emailPlaceholder: 'you@example.com',
        notifyLabel: 'Notify me when you launch',
        button: 'Join the waitlist',
        success: 'You’re on the list — thank you! We’ll be in touch at launch.',
      },
      // Popup shown when someone taps Download / App Store / Google Play before launch.
      popup: {
        title: 'Vaulmo isn’t live just yet',
        body: 'We’re putting the finishing touches to the app. Leave your details and we’ll email you the moment it’s ready to download.',
      },
    },
  },
  {
    slug: 'home',
    title: 'Home',
    content: {
      heroPill: 'Bank-level encryption · Family-ready',
      heroTitle: 'Your family’s important documents,',
      heroTitleAccent: 'locked down.',
      heroLead: 'Vaulmo keeps passports, policies, warranties and wills secure, organised and always to hand — with smart scanning and reminders so nothing important ever slips.',
      heroNote: 'Coming soon to iOS & Android. Free to download.',
      featuresEyebrow: 'Everything in one place',
      featuresTitle: 'Built to keep life’s paperwork safe',
      featuresIntro: 'Snap a photo and Vaulmo reads the details, files it, and reminds you before anything expires.',
      features: [
        { title: 'Bank-level security', body: 'Documents are encrypted, protected by two-factor login, and only ever visible to you and the people you choose.' },
        { title: 'Smart scanning', body: 'Photograph a document and Vaulmo pulls out the key dates and details automatically — no typing.' },
        { title: 'Never miss a renewal', body: 'Passports, insurance, warranties, MOTs — get reminded in good time, only after you confirm the dates.' },
        { title: 'Family & next of kin', body: 'Share the right documents with your household, and nominate a trusted next of kin for emergencies.' },
      ],
      ctaEyebrow: 'Get started',
      ctaTitle: 'Bring your paperwork into one secure place',
      ctaIntro: 'Download Vaulmo and set up your family vault in minutes.',
    },
  },
  {
    slug: 'features',
    title: 'Features',
    content: {
      title: 'Everything Vaulmo does for you',
      intro: 'One secure home for the documents, dates and details your family relies on — with the smarts to keep everything organised and remind you before anything slips.',
      sections: [
        { image: 'scan', heading: 'Scan & organise instantly', body: 'Photograph or upload any document — passport, insurance policy, warranty, payslip, tenancy — and Vaulmo reads the key details, works out what it is, files it in the right category and makes it searchable in seconds. No typing, no folders to maintain. It handles photos, PDFs and multi-page scans, and even builds a passport-ready photo for you.' },
        { image: 'reminders', heading: 'Never miss a renewal', body: 'Vaulmo tracks expiry and renewal dates across your documents, MOT, road tax, insurance, warranties and subscriptions, and brings them together into one clear “what’s coming up” view — grouped by how soon they need attention. You get reminded in good time, and only after you’ve confirmed the dates, so alerts are always accurate.' },
        { image: 'assistant', heading: 'Ask Vaulmo anything', body: 'Ask plain-English questions like “when does my passport expire?”, “what renews in the next six months?” or “where’s my home insurance policy?” and get an instant answer drawn only from your own vault — with a link to the source document. It’s the fastest way to find what you need without digging through drawers or inboxes.' },
        { image: 'family', heading: 'Family & emergency access', body: 'Keep your whole household’s documents together and file them by person. Nominate a trusted next of kin who can request access in a genuine emergency — but only ever with your approval, limited to what you allow, and fully logged. Nothing is shared by default; you stay in control of who sees what.' },
        { image: 'vault', heading: 'Password vault', body: 'Store passwords, card details, PINs and secure notes in an encrypted vault that only you can open — protected by your login and, on mobile, your fingerprint or Face ID. Everything is encrypted before it’s stored, and even our staff can’t read it.' },
        { image: 'passport', heading: 'Passport & ID photos', body: 'Take a compliant passport photo right in the app. Vaulmo detects your face, removes the background and makes it white, then crops and sizes it to the 35×45mm standard — ready to download or print, or to keep in your vault.' },
        { image: 'connect', heading: 'Smart capture from email', body: 'Connect your inbox (with your permission, read-only) and Vaulmo can spot travel bookings, receipts, warranties and subscriptions automatically — surfacing them for you to confirm before anything is saved. Less manual entry, nothing added behind your back.' },
        { image: 'security', heading: 'Secure by design', body: 'Bank-grade encryption, two-factor authentication, a biometric app lock and a full activity log come as standard — because Vaulmo holds the documents that matter most. Read more on the Security page.' },
      ],
    },
  },
  {
    slug: 'security',
    title: 'Security',
    content: {
      title: 'Security you can trust with what matters most',
      intro: 'Vaulmo is built security-first, because it holds the documents that matter most. Here’s how we keep your family’s information safe — in plain English.',
      points: [
        'Encryption in transit (HTTPS/TLS) and at rest for your sensitive data',
        'Passwords, cards and secure notes encrypted with AES-256 before storage',
        'Two-factor authentication (2FA) available on every account, mandatory for staff',
        'Biometric app lock — Face ID or fingerprint — on mobile',
        'Signed-in device list you can review and revoke at any time',
        'You decide who sees what — nothing is shared by default',
        'A full, tamper-evident activity log of every action on your account',
        'Staff cannot casually view your document contents; any exceptional access is authorised and logged',
      ],
      sections: [
        { heading: 'Encryption everywhere', body: 'Your connection to Vaulmo is always encrypted with HTTPS/TLS, so nothing travels in the clear. Sensitive data is encrypted at rest, and your passwords, card numbers, PINs and secure notes are encrypted with AES-256 — a bank-grade standard — before they are ever written to our database.' },
        { heading: 'Strong authentication', body: 'Protect your account with two-factor authentication (an app-based one-time code), so a password alone is never enough to get in. On mobile you can add a biometric lock — Face ID or your fingerprint — so the app only opens for you. Administrator accounts are required to use 2FA.' },
        { heading: 'You are in control of access', body: 'Nothing is shared by default. Family members and next of kin only ever see what you explicitly allow. Emergency access can only be granted after your approval and a review, is limited and time-boxed, and every step is recorded.' },
        { heading: 'Least-privilege, audited operations', body: 'Our own team operates on a least-privilege basis and cannot casually browse your documents. Any exceptional access — for example to help resolve a support issue you’ve raised — is authorised and written to an audit trail.' },
        { heading: 'Device and session management', body: 'See every device signed in to your account and sign any of them out remotely — useful if you lose a phone or use a shared computer. Sessions expire and can be revoked individually or all at once.' },
        { heading: 'Your data, your choice', body: 'You can export a copy of your data or request deletion at any time from within the app. We don’t sell your data, and we only process it to provide the service you’ve asked for.' },
        { heading: 'Responsible disclosure', body: 'If you believe you’ve found a security issue, we want to hear from you. Email security@vaulmo.com and we’ll work with you to investigate and resolve it quickly.' },
      ],
    },
  },
  {
    slug: 'privacy',
    title: 'Privacy',
    content: {
      title: 'Privacy policy',
      updated: 'Last updated: August 2026',
      intro: 'Your documents are yours. This policy explains, in plain English, what we collect, why, how we protect it and the control you have. If anything is unclear, contact us at privacy@vaulmo.com.',
      sections: [
        { heading: 'Who we are', body: 'Vaulmo provides a secure digital vault for your family’s important documents, dates and details, available on the web and on iOS and Android. In this policy, “we”, “us” and “Vaulmo” refer to the provider of the service, and “you” refers to the account holder.' },
        { heading: 'What we collect', body: 'The documents, images and details you choose to add to your vault; the account information needed to run the service (your name, email address and security settings such as two-factor authentication); and basic technical information such as device type and log data used to keep the service secure and reliable. We collect only what we need to provide Vaulmo to you.' },
        { heading: 'Why we process your data (our lawful basis)', body: 'We process your data to perform our contract with you — providing the vault, extracting the document details you ask us to, sending the reminders you set up, and keeping your account secure. Where we rely on your consent (for example to connect your email inbox), you can withdraw it at any time.' },
        { heading: 'How we protect it', body: 'Your connection is encrypted with HTTPS/TLS, sensitive data is encrypted at rest, and passwords and secure notes are encrypted with AES-256 before storage. Access to systems is least-privilege and audited. See the Security page for more detail.' },
        { heading: 'Who can see your data', body: 'Only you, and the people you explicitly grant access to (such as a nominated next of kin in an approved emergency). Our staff cannot casually browse your document contents; any exceptional access is authorised and logged. We do not sell your data, and we do not use your documents to train advertising profiles.' },
        { heading: 'Connected services (email import)', body: 'If you choose to connect an email inbox, we request read-only access and use it solely to detect items like travel, receipts and warranties, which you confirm before anything is saved. You can disconnect at any time, which stops any further access.' },
        { heading: 'Third parties and processors', body: 'We use a small number of trusted service providers (for example, cloud hosting, and — where you enable them — email and payment providers) strictly to operate the service. They act on our instructions and are bound to protect your data. We do not share your documents with third parties for their own purposes.' },
        { heading: 'International transfers', body: 'Where data is processed outside your country, we put appropriate safeguards in place so it continues to receive an equivalent level of protection.' },
        { heading: 'How long we keep it', body: 'We keep your data for as long as your account is active. If you delete an item or your account, we remove it, subject to short retention needed for security, backups and legal obligations, after which it is deleted.' },
        { heading: 'Your rights', body: 'You can access and export a copy of your data, correct it, or request its deletion at any time from within the app. Depending on where you live, you may also have rights to object to or restrict certain processing. Contact privacy@vaulmo.com to exercise any of these; we’ll respond within the timeframes required by law.' },
        { heading: 'Cookies', body: 'The website uses only the cookies needed to make it work and to keep you signed in. We don’t use advertising cookies.' },
        { heading: 'Children', body: 'Vaulmo is intended for adults managing a household’s documents and is not directed at children. You may store documents relating to children in your family, but accounts are for adults.' },
        { heading: 'Changes to this policy', body: 'If we make material changes we’ll update this page and, where appropriate, notify you in the app. The “last updated” date above always reflects the current version.' },
        { heading: 'Contact', body: 'Questions or requests about your privacy? Email privacy@vaulmo.com and we’ll be glad to help.' },
      ],
    },
  },
  {
    slug: 'support',
    title: 'Support',
    content: {
      title: 'Help & support',
      intro: 'We’re here to help you get the most out of Vaulmo — whether you’re just getting started or need a hand with something specific.',
      channels: [
        { name: 'Email support', detail: 'Email support@vaulmo.com and we aim to reply within one business day. Include your account email and a description of the issue (and a screenshot if you can) so we can help faster.' },
        { name: 'In-app help & FAQ', detail: 'Open the app and visit Help & FAQ for step-by-step guides and answers to the most common questions — often the quickest way to get unstuck.' },
        { name: 'Feature requests & feedback', detail: 'Got an idea or something that would make Vaulmo better for your family? Email feedback@vaulmo.com — we read every message and it genuinely shapes what we build.' },
        { name: 'Security issues', detail: 'If you believe you’ve found a security vulnerability, please email security@vaulmo.com so we can investigate promptly.' },
        { name: 'Service status', detail: 'We’ll post any planned maintenance or service updates and notify you in the app if anything needs your attention.' },
      ],
      sections: [
        { heading: 'Getting started', body: 'Create your account, answer a few quick questions so Vaulmo knows which documents to recommend, then scan or upload your first document. The app guides you step by step, and your completion score shows what’s left to add — with no pressure.' },
        { heading: 'Common fixes', body: 'If a scan doesn’t read correctly, retake the photo in good light with the whole document in frame — you can always edit the details by hand. If you’re not receiving reminders, check your notification settings and quiet hours. If you can’t sign in, use “forgot password”, and make sure your two-factor code is from the right authenticator.' },
        { heading: 'Response times', body: 'We aim to respond to all support emails within one business day. Security reports are prioritised.' },
        { heading: 'Your data', body: 'You can export your data or request account deletion at any time from within the app — see the Privacy page for details.' },
      ],
      note: 'Looking for a quick answer? Check the FAQs page first — most questions are covered there.',
    },
  },
  {
    slug: 'about',
    title: 'About',
    content: {
      title: 'About Vaulmo',
      intro: 'Vaulmo is a personal life operating system — a secure digital vault for your family’s most important documents, dates and details, designed to give households genuine peace of mind.',
      sections: [
        { heading: 'The problem we set out to solve', body: 'Modern family life generates a mountain of paperwork: passports and driving licences, insurance policies and warranties, tenancy agreements and mortgage papers, MOT and tax reminders, payslips, school letters, medical records and more. It ends up scattered across drawers, email inboxes, cloud folders and the occasional shoebox. When you actually need something — a policy number at the roadside, a passport expiry date before booking a holiday, a warranty when an appliance fails — it’s never where you expect, and important renewals quietly slip past until it’s too late. We built Vaulmo because that everyday low-level stress is completely avoidable.' },
        { heading: 'What Vaulmo does', body: 'Vaulmo brings all of it into one secure, organised place. You scan or photograph a document and Vaulmo reads the important details, works out what it is, files it, and makes it instantly searchable. It tracks the dates that matter and reminds you in good time, so nothing important is ever missed. And when you have a question — “when does my passport expire?”, “what renews next month?” — you can simply ask, and get an answer drawn only from your own information. It’s the difference between hoping you’re on top of things and actually knowing you are.' },
        { heading: 'Security is the foundation, not an afterthought', body: 'Because Vaulmo holds the documents that matter most, we built it security-first from day one. Your data is encrypted in transit and at rest, protected by two-factor authentication and an optional biometric lock, and governed by strict, least-privilege access — our own team cannot casually view your documents. Nothing is shared without your say-so, and every action on your account is logged. We believe privacy is a feature you can feel, not fine print you have to trust.' },
        { heading: 'Built for the whole household', body: 'Real life isn’t a single person with a single folder — it’s a household. Vaulmo lets you organise documents by family member, keep everyone’s essentials together, and nominate a trusted next of kin who can reach what they need in a genuine emergency, always with your approval. It’s designed to be simple enough for everyone in the family to use, on whatever device they have to hand.' },
        { heading: 'What we believe', body: 'We believe your documents are yours, and should stay that way. We believe good software should reduce mental load, not add to it. And we believe the important, boring, easy-to-forget admin of family life deserves a tool that’s calm, clear and genuinely trustworthy. Those principles guide every decision we make — from how we handle your data to the words we choose in the app.' },
        { heading: 'Where we’re headed', body: 'Vaulmo is growing quickly, guided by the households who use it. We’re continually adding smarter capture, deeper reminders, and more of the everyday tools families need in one trusted place — always with the same commitment to security and simplicity. If you have an idea for what would help your family, we’d genuinely love to hear it.' },
      ],
    },
  },
  {
    slug: 'contact',
    title: 'Contact',
    content: {
      title: 'Contact us',
      intro: 'Questions, feedback or press enquiries — we’d love to hear from you.',
      email: 'hello@vaulmo.com',
      supportEmail: 'support@vaulmo.com',
      phone: '',
      address: '',
      hours: 'Monday to Friday, 9am–5pm',
    },
  },
  {
    slug: 'faq',
    title: 'FAQs',
    content: {
      title: 'Frequently asked questions',
      intro: 'The answers to the questions we hear most. Can’t find what you need? Email support@vaulmo.com.',
      items: [
        { q: 'Is my data secure?', a: 'Yes. Your connection is encrypted with HTTPS/TLS, sensitive data is encrypted at rest, and passwords and secure notes are encrypted with AES-256. Access is protected by two-factor authentication and an optional biometric lock, and nothing is shared without your say-so.' },
        { q: 'Can Vaulmo staff see my documents?', a: 'No — not casually. Our team operates on a least-privilege basis and cannot browse your document contents. Any exceptional access, for example to resolve a support issue you’ve raised, is authorised and written to an audit log.' },
        { q: 'How does scanning work?', a: 'Photograph or upload a document and Vaulmo reads the key details automatically, works out what type it is, and files it. You always confirm what it found before anything is saved, and you can edit or add details by hand.' },
        { q: 'What types of documents can I store?', a: 'Anything important — passports and ID, driving licences, insurance policies, warranties, tenancy and mortgage papers, MOT and tax, payslips, medical letters, wills and more. You can store photos, PDFs and multi-page scans.' },
        { q: 'What does it cost?', a: 'Vaulmo is free to download. Subscription plans unlock additional features and storage — you’ll always see the price and exactly what’s included before you choose, with no surprises.' },
        { q: 'Can my whole family use it?', a: 'Yes. You can organise documents by household member (for example each child’s passport), keep everyone’s essentials together, and nominate a trusted next of kin for emergencies.' },
        { q: 'What happens in an emergency?', a: 'A nominated next of kin can request access. It only becomes active after your approval and a review, and even then it’s limited to what you allow and time-boxed. Every step is recorded.' },
        { q: 'Which devices are supported?', a: 'Vaulmo works on the web and on iOS and Android, all signed in to the same account, so your vault is the same wherever you are.' },
        { q: 'Do you sell my data or show ads?', a: 'No. We don’t sell your data and we don’t use your documents to build advertising profiles. We only process your information to provide the service you’ve asked for.' },
        { q: 'Can I export or delete my data?', a: 'Yes. You can export a copy of your data or request account deletion at any time from within the app. See the Privacy page for details.' },
        { q: 'How do reminders work?', a: 'Vaulmo tracks expiry and renewal dates from your documents, assets and subscriptions, and reminds you in good time — but only after you’ve confirmed the dates, so alerts are always accurate. You can also add your own reminders and set them to repeat.' },
        { q: 'Can Vaulmo read my emails to find documents?', a: 'Only if you choose to connect an inbox, and only with read-only access. It looks for things like travel bookings, receipts and warranties and surfaces them for you to confirm — nothing is added without your approval, and you can disconnect at any time.' },
        { q: 'What is the password vault?', a: 'A private, encrypted place to store passwords, card details, PINs and secure notes. Everything is encrypted before it’s stored, only you can open it, and on mobile it sits behind your biometric lock.' },
        { q: 'Can I take a passport photo in the app?', a: 'Yes. Vaulmo detects your face, makes the background white and crops the photo to the 35×45mm passport standard — ready to download, print or keep in your vault. For best results, use a plain wall and even lighting.' },
        { q: 'Do I need to be online to use Vaulmo?', a: 'You need a connection to sign in, scan and sync. Once documents are in your vault they’re available across your signed-in devices.' },
        { q: 'How is Vaulmo different from cloud storage?', a: 'Cloud storage gives you folders; Vaulmo gives you understanding. It reads your documents, files them, tracks the important dates, reminds you, and answers questions — so it’s an organiser and assistant, not just a place to dump files.' },
        { q: 'What is two-factor authentication (2FA) and should I use it?', a: 'It’s a second step at sign-in — a one-time code from an authenticator app — so a password alone isn’t enough to get in. We strongly recommend turning it on; it’s one of the best ways to protect your account.' },
        { q: 'I lost my phone — is my vault safe?', a: 'Yes. Your data lives in your account, not only on the device, and the mobile app is protected by a biometric lock. You can also sign out the lost device remotely from the signed-in devices list.' },
        { q: 'Can I cancel my subscription?', a: 'Yes, at any time from the billing screen. You keep access until the end of your current period, and you’ll always be able to view and export what you’ve stored.' },
        { q: 'Can I sign in with Google, Apple or Microsoft?', a: 'Yes — social sign-in is supported. You can also use a regular email and password. Either way, the same security protections apply.' },
        { q: 'Is there a storage limit?', a: 'Free and paid plans include generous storage; if a plan has a limit you’ll see it clearly, and you can upgrade at any time. Your existing documents are never held hostage.' },
        { q: 'How do I get help if I’m stuck?', a: 'Check this FAQ and the in-app Help first, and if you still need a hand, email support@vaulmo.com — we aim to reply within one business day.' },
      ],
    },
  },
  {
    slug: 'terms',
    title: 'Terms & Conditions',
    content: {
      title: 'Terms & Conditions',
      updated: 'Last updated: August 2026',
      intro: 'These terms govern your use of Vaulmo. By creating an account or using the service, you agree to them. Please read them alongside our Privacy Policy.',
      sections: [
        { heading: '1. About these terms', body: 'These Terms & Conditions form an agreement between you and Vaulmo (“we”, “us”). They apply to your use of the Vaulmo apps and website. If you don’t agree with them, please don’t use the service.' },
        { heading: '2. Your account', body: 'You must provide accurate information when you register and keep your login details secure. You’re responsible for activity on your account. Tell us promptly at support@vaulmo.com if you suspect unauthorised use. You must be an adult to hold an account.' },
        { heading: '3. The service', body: 'Vaulmo provides a secure digital vault to store, organise and be reminded about your documents and related information. We work hard to keep the service accurate and available, but features may evolve and we may occasionally need to perform maintenance.' },
        { heading: '4. Your content', body: 'The documents and information you add remain yours. You grant us only the limited permissions needed to store, process and display that content to you and the people you authorise, and to provide features you use (such as reading document details or sending reminders). You’re responsible for having the right to store the content you upload.' },
        { heading: '5. Acceptable use', body: 'You agree not to misuse the service — for example by uploading unlawful content, attempting to breach security, interfering with other users, or using the service to store material you have no right to hold. We may suspend or close accounts that break these rules.' },
        { heading: '6. Subscriptions and payment', body: 'Vaulmo is free to download. Some features require a paid subscription. Prices, billing periods and what’s included are shown before you subscribe. Subscriptions renew automatically unless cancelled, and you can cancel at any time from the billing screen; access continues until the end of the current period. Applicable taxes may apply.' },
        { heading: '7. Cancellation and your data', body: 'You can stop using Vaulmo at any time. You can export your data or request account deletion from within the app. On deletion we remove your data, subject to short retention needed for security, backups and legal obligations.' },
        { heading: '8. Availability and changes', body: 'We aim for high availability but don’t guarantee the service will be uninterrupted or error-free. We may update, add or remove features, and will give reasonable notice of significant changes where we can.' },
        { heading: '9. Intellectual property', body: 'The Vaulmo apps, website, branding and software are owned by us and protected by law. These terms don’t transfer any of our intellectual property to you; you receive a limited right to use the service as intended.' },
        { heading: '10. Disclaimers', body: 'Vaulmo is a tool to help you organise information; it is not a substitute for professional, legal, financial or medical advice, and reminders are provided as a convenience. Please always verify critical dates and details independently.' },
        { heading: '11. Limitation of liability', body: 'To the extent permitted by law, we are not liable for indirect or consequential losses, or for loss arising from your failure to keep your login secure or to verify important information. Nothing in these terms limits liability that cannot be limited by law.' },
        { heading: '12. Termination', body: 'You may close your account at any time. We may suspend or end access if you materially breach these terms or use the service unlawfully, giving notice where appropriate.' },
        { heading: '13. Changes to these terms', body: 'We may update these terms from time to time. If we make material changes we’ll update this page and, where appropriate, notify you in the app. Continuing to use Vaulmo after changes take effect means you accept the updated terms.' },
        { heading: '14. Governing law & contact', body: 'These terms are governed by the laws applicable in our place of establishment, without affecting any mandatory consumer protections you have where you live. Questions? Email legal@vaulmo.com.' },
      ],
    },
  },
];

export const defaultForSlug = (slug: string): SitePageSeed | undefined => DEFAULT_SITE_PAGES.find((p) => p.slug === slug);
